---
- name: Pull Kubernetes manifest files
  hosts: k8s-server
  tasks:
    - name: Copy Kubernetes manifest files to the Node server
      copy:
        src: /var/lib/jenkins/workspace/{{ pipeline_name }}/{{ item }} #USE ENV VAIRALBE IN pipeline_name
        dest: /root/k8s-manifest/{{ item }}
      with_items:
        - deployment.yml
        - service.yml
