apiVersion: v1
kind: Service
metadata:
  name: new-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30080 # Custom NodePort for external access

# apiVersion: v1
# kind: Service
# metadata:
#   name: valaxy-service
#   labels:
#     app: regapp 
# spec:
#   selector:
#     app: regapp 

#   ports:
#     - port: 8080
#       targetPort: 8080

#   type: LoadBalancer
